import './globals.css'
import Image from "next/image";
import { getSiteData } from "./data";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getSiteData();
  return (
    <html lang="en">
      <body>
        <header className="relative text-white text-shadow-black">
          {data.header && (
            <Image
              src={data.header.url}
              alt={data.header.alternativeText ?? ""}
              fill={true}
              placeholder={data.header.placeholder ? "blur" : "empty"}
              blurDataURL={data.header.placeholder ?? undefined}
              className="absolute -z-10 object-cover"
            ></Image>
          )}
          <div className="py-24 flex flex-col items-center gap-8 justify-center">
            <div className="bg-black/20 p-2 rounded">
              <h1 className="p-8 text-center text-6xl uppercase tracking-wider border border-2 border-gray-300 rounded">
                {data.title}
              </h1>
            </div>
            <div className="text-xl text-center italic bg-black/10 px-8 py-4 rounded">
              {data.subtitle}
            </div>
          </div>
          <nav className="p-4 flex gap-8 text-xl justify-center rounded max-w-fit mx-auto">
            <Link className="nav-item" href="/">
              Home
            </Link>
            {data.categories.map((category) => (
              <Link
                className="nav-item"
                key={category.slug}
                href={`/${category.slug}`}
              >
                {category.name}
              </Link>
            ))}
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
